### ISSUE TITLE
The OpenShift pipeline build-power-mgr fails

### ISSUE THREAD

**Issue by spisarski** [openshift-telco/ocp-intel-vcmts#8]
Here are the logs captured from the failed builder pod for build-power-mgr:

Package jansson-2.14-1.el8.x86_64 is already installed.
No match for argument: libvirt
Error: Unable to find a match: libvirt

**Comment by adetalhouet** [comment]
Thanks for reporting this. It is a leftover.
The build doesn't yet work and is actually not needed for now.
